excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ignorantspeculator.github.io
title: ignorantspeculator
tagline: A log of everyday life
description: My awesome new site
paginate: 5